name: CI

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    
    steps:
    - run: echo $RUNNER_TOOL_CACHE
    - run: ls $RUNNER_TOOL_CACHE/Python
    - run: ls $RUNNER_TOOL_CACHE/PyPy
  mac:
    runs-on: macOS-latest
    
    steps:
    - run: echo $RUNNER_TOOL_CACHE
    - run: ls $RUNNER_TOOL_CACHE/Python
    - run: ls $RUNNER_TOOL_CACHE/PyPy
  win:
    runs-on: windows-latest
    
    steps:
    - run: echo %RUNNER_TOOL_CACHE%
    - run: ls $RUNNER_TOOL_CACHE/Python
      shell: bash
    - run: ls $RUNNER_TOOL_CACHE/PyPy
      shell: bash
